services:
  front:
    hostname: sysgarantiafronthost
    image: br.albatross.sysgarantia.front-i
    container_name: br.albatross.sysgarantia.front-dc
    build:
      context: ./front
    networks:
      - sysgarantia-network
    restart: always
    ports:
      - ${SYSGARANTIA_FRONT_PORT}:3000
    volumes:
      - br.albatross.sysgarantia.front-vol:/var/log/nginx/:rw
    depends_on:
      api:
        condition: service_started
      keycloak:
        condition: service_started

  keycloak:
    hostname: keycloakhost
    image: br.albatross.sysgarantia.keycloak-i
    container_name: br.albatross.sysgarantia.keycloak-dc
    build:
      context: ./keycloak
    networks:
      - sysgarantia-network
    restart: always
    ports:
      - ${SYSGARANTIA_KEYCLOAK_PORT}:8443
    depends_on:
      db:
        condition: service_started
    environment:
      - SYSGARANTIA_API_DB_HOST=${SYSGARANTIA_API_DB_HOST}
      - SYSGARANTIA_API_DB_PORT=${SYSGARANTIA_API_DB_PORT}
      - SYSGARANTIA_API_DB_USERNAME=${SYSGARANTIA_API_DB_USERNAME}
      - SYSGARANTIA_API_DB_PASSWORD=${SYSGARANTIA_API_DB_PASSWORD}
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HTTPS_PORT=${SYSGARANTIA_KEYCLOAK_PORT}
      - KC_HOSTNAME=${PUBLIC_IP_ADDRESS}
#      - KC_HOSTNAME_URL=https://PUBLIC_IP_ADDRESS:${SYSGARANTIA_FRONT_PORT}/keycloak
#      - KC_HOSTNAME_ADMIN_URL=https://PUBLIC_IP_ADDRESS:${SYSGARANTIA_FRONT_PORT}/keycloak

  kafka1:
    hostname: kafka1host
    image: apache/kafka:3.9.0
    container_name: br.albatross.sysgarantia.messaging.kafka-1-dc
    networks:
      - sysgarantia-network
    restart: always
    volumes:
      - br.albatross.sysgarantia.messaging.kafka1-data-vol:/var/lib/kafka/data/
      - br.albatross.sysgarantia.messaging.kafka1-logs-vol:/tmp/kafka-logs/
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka1:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,HOST:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  api:
    hostname: sysgarantiaapihost
    image: br.albatross.sysgarantia.backend.api-i
    container_name: br.albatross.sysgarantia.backend.api-dc
    build:
      context: ./api
    restart: always
    networks:
      - sysgarantia-network
    depends_on:
      db:
        condition: service_started
      kafka1:
        condition: service_started
        required: true
      keycloak:
        condition: service_started
        required: true
    environment:
      - SYSGARANTIA_API_DB_USERNAME=${SYSGARANTIA_API_DB_USERNAME}
      - SYSGARANTIA_API_DB_PASSWORD=${SYSGARANTIA_API_DB_PASSWORD}
      - SYSGARANTIA_API_DB_HOST=${SYSGARANTIA_API_DB_HOST}
      - SYSGARANTIA_API_DB_PORT=${SYSGARANTIA_API_DB_PORT}

      - SYSGARANTIA_OTRS_ZNUNY_DB_USERNAME=${SYSGARANTIA_OTRS_ZNUNY_DB_USERNAME}
      - SYSGARANTIA_OTRS_ZNUNY_DB_PASSWORD=${SYSGARANTIA_OTRS_ZNUNY_DB_PASSWORD}
      - SYSGARANTIA_OTRS_ZNUNY_DB_HOST=${SYSGARANTIA_OTRS_ZNUNY_DB_HOST}
      - SYSGARANTIA_OTRS_ZNUNY_DB_PORT=${SYSGARANTIA_OTRS_ZNUNY_DB_PORT}
      - SYSGARANTIA_OTRS_ZNUNY_DB_NAME=${SYSGARANTIA_OTRS_ZNUNY_DB_NAME}

      - SYSGARANTIA_MAIL_SMTP_FROM=${SYSGARANTIA_MAIL_SMTP_FROM}
      - SYSGARANTIA_MAIL_SMTP_USERNAME=${SYSGARANTIA_MAIL_SMTP_USERNAME}
      - SYSGARANTIA_MAIL_SMTP_PASSWORD=${SYSGARANTIA_MAIL_SMTP_PASSWORD}
      - SYSGARANTIA_MAIL_SMTP_HOST=${SYSGARANTIA_MAIL_SMTP_HOST}
      - SYSGARANTIA_MAIL_SMTP_PORT=${SYSGARANTIA_MAIL_SMTP_PORT}
      - SYSGARANTIA_MAIL_SMTP_TLS=${SYSGARANTIA_MAIL_SMTP_TLS}
      - SYSGARANTIA_MAIL_SMTP_START_TLS=${SYSGARANTIA_MAIL_SMTP_START_TLS}
      - SYSGARANTIA_MAIL_SMTP_MOCK=${SYSGARANTIA_MAIL_SMTP_MOCK}

      - SYSGARANTIA_MESSAGING_KAFKA_BOOTSTRAP_SERVERS=${SYSGARANTIA_MESSAGING_KAFKA_BOOTSTRAP_SERVERS}

      - SYSGARANTIA_MAIL_SMTP_MAX_ATTACHMENT_SIZE=${SYSGARANTIA_MAIL_SMTP_MAX_ATTACHMENT_SIZE}
      - SYSGARANTIA_API_HTTP_CORS_ORIGIN=${SYSGARANTIA_API_HTTP_CORS_ORIGIN}

  db:
    hostname: sysgarantiaapidbhost
    image: mariadb:11.4.5-noble
    container_name: br.albatross.sysgarantia.api.db-dc
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${SYSGARANTIA_API_DB_PASSWORD}
    networks:
      - sysgarantia-network
    volumes:
      - br.albatross.sysgarantia.api.db-data-vol:/var/lib/mysql/data/

networks:
  sysgarantia-network:
    name: sysgarantia-network
    driver: bridge

volumes:
  br.albatross.sysgarantia.front-vol:
  br.albatross.sysgarantia.messaging.kafka1-data-vol:
  br.albatross.sysgarantia.messaging.kafka1-logs-vol:
  br.albatross.sysgarantia.api.db-data-vol:
  














