services:
  front:
    hostname: sysgarantiafronthost
    image: br.albatross.sysgarantia.front-i
    container_name: br.albatross.sysgarantia.front-dc
    build:
      context: ./front
    networks:
      - sysgarantia-network
    restart: always
    ports:
      - ${SYSGARANTIA_FRONT_PORT}:3000
    depends_on:
      api:
        condition: service_started
      keycloak:
        condition: service_started

  keycloak:
    hostname: keycloakhost
    image: br.albatross.sysgarantia.keycloak-i
    container_name: br.albatross.sysgarantia.keycloak-dc
    build:
      context: ./keycloak
    networks:
      - sysgarantia-network
    restart: always
    ports:
      - ${SYSGARANTIA_KEYCLOAK_PORT}:8443
#    depends_on:
#      db:
#        condition: service_started
    environment:
      - SYSGARANTIA_API_DB_HOST=${SYSGARANTIA_API_DB_HOST}
      - SYSGARANTIA_API_DB_PORT=${SYSGARANTIA_API_DB_PORT}
      - SYSGARANTIA_API_DB_USERNAME=${SYSGARANTIA_API_DB_USERNAME}
      - SYSGARANTIA_API_DB_PASSWORD=${SYSGARANTIA_API_DB_PASSWORD}
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HTTPS_PORT=${SYSGARANTIA_KEYCLOAK_PORT}

  kafka1:
    hostname: kafka1host
    image: apache/kafka:3.9.0
    container_name: br.albatross.sysgarantia.messaging.kafka-1-dc
    networks:
      - sysgarantia-network
    restart: always

  api:
    hostname: sysgarantiaapihost
    image: br.albatross.sysgarantia.backend.api-i
    container_name: br.albatross.sysgarantia.backend.api-dc
    build:
      context: ./api
    restart: always
    networks:
      - sysgarantia-network
    depends_on:
#      db:
#        condition: service_started
      kafka1:
        condition: service_started
      keycloak:
        condition: service_started
    environment:
      - SYSGARANTIA_API_DB_USERNAME=${SYSGARANTIA_API_DB_USERNAME}
      - SYSGARANTIA_API_DB_PASSWORD=${SYSGARANTIA_API_DB_PASSWORD}
      - SYSGARANTIA_API_DB_HOST=${SYSGARANTIA_API_DB_HOST}
      - SYSGARANTIA_API_DB_PORT=${SYSGARANTIA_API_DB_PORT}

      - SYSGARANTIA_OTRS_ZNUNY_DB_USERNAME=${SYSGARANTIA_OTRS_ZNUNY_DB_USERNAME}
      - SYSGARANTIA_OTRS_ZNUNY_DB_PASSWORD=${SYSGARANTIA_OTRS_ZNUNY_DB_PASSWORD}
      - SYSGARANTIA_OTRS_ZNUNY_DB_HOST=${SYSGARANTIA_OTRS_ZNUNY_DB_HOST}
      - SYSGARANTIA_OTRS_ZNUNY_DB_PORT=${SYSGARANTIA_OTRS_ZNUNY_DB_PORT}
      - SYSGARANTIA_OTRS_ZNUNY_DB_NAME=${SYSGARANTIA_OTRS_ZNUNY_DB_NAME}

      - SYSGARANTIA_MAIL_SMTP_USERNAME=${SYSGARANTIA_MAIL_SMTP_USERNAME}
      - SYSGARANTIA_MAIL_SMTP_PASSWORD=${SYSGARANTIA_MAIL_SMTP_PASSWORD}
      - SYSGARANTIA_MAIL_SMTP_HOST=${SYSGARANTIA_MAIL_SMTP_HOST}
      - SYSGARANTIA_MAIL_SMTP_PORT=${SYSGARANTIA_MAIL_SMTP_PORT}
      - SYSGARANTIA_MAIL_SMTP_TLS=${SYSGARANTIA_MAIL_SMTP_TLS}
      - SYSGARANTIA_MAIL_SMTP_START_TLS=${SYSGARANTIA_MAIL_SMTP_START_TLS}
      - SYSGARANTIA_MAIL_SMTP_MOCK=${SYSGARANTIA_MAIL_SMTP_MOCK}

      - SYSGARANTIA_MESSAGING_KAFKA_BOOTSTRAP_SERVER_HOST=${SYSGARANTIA_MESSAGING_KAFKA_BOOTSTRAP_SERVER_HOST}
      - SYSGARANTIA_MESSAGING_KAFKA_BOOTSTRAP_SERVER_PORT=${SYSGARANTIA_MESSAGING_KAFKA_BOOTSTRAP_SERVER_PORT}

      - SYSGARANTIA_MAIL_SMTP_MAX_ATTACHMENT_SIZE=${SYSGARANTIA_MAIL_SMTP_MAX_ATTACHMENT_SIZE}

  db:
    hostname: sysgarantiaapidbhost
    image: mariadb:11.4.5-noble
    container_name: br.albatross.sysgarantia.api.db-dc
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${SYSGARANTIA_API_DB_PASSWORD}
    build:
      context: ./db
    networks:
      - sysgarantia-network

networks:
  sysgarantia-network:
    name: sysgarantia-network
    driver: bridge

















